


spring:
  redis:
    host: ${redis.url}
    port: 6379

  mail:
    #    host: smtp.gmail.com
    #    port: 587
    #    username: ${google.email.sender}
    #    password: ${google.app.pw}
    host: mailhog
    port: 1025
    properties:
      mail:
        smtp:
          #          auth: true
          auth: false
          starttls:
            #            enable: true
            #            required: true
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분