


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: ${aws.db.url}
  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  logging:
    level:
      root: info
      org.hibernate.SQL: DEBUG
      org.hibernate.type:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSSSSS} %p %c{1.} [%t] %m%n"



  redis:
    host: ${redis.url}
    port: 6379
    publish:
      rate: 10000
    key:
      sms: "stream:sms"
      email: "stream:email"
      fcm: "stream:fcm"
    group:
      sms: "sms"
      email: "email"
      fcm: "fcm"

  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    queue:
      sms: "queue:sms"
      email: "queue:email"
      fcm: "queue:fcm"
    exchange:
      sms: "exchange:sms"
      email: "exchange:email"
      fcm: "exchange:fcm"
    routing:
      sms: "key:sms"
      email: "key:email"
      fcm: "key:fcm"

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}:9092
    topic:
      email: "email"
      sms: "sms"
      fcm: "fcm"

oauth2:
  fcm:
    projectId: ${fcm.project.id}