


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: ${aws.db.url}
  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  logging:
    level:
      #      root: info
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace


  redis:
#    host: localhost
    host: ${redis.url}
    port: 6379
    publish:
      rate: 10000
    key: "swCapstoneStream"
    group:
      sms: "sms"
      email: "email"
      fcm: "fcm"

oauth2:
  fcm:
    projectId: ${fcm.project.id}