


spring:
  redis:
    host: ${redis.url}
    port: 6379
    key: "stream:sms"

naver:
  service:
    id: ${naver.service.id}
  send:
    phoneNum: ${naver.from}
  access:
    key: ${naver.access.key}
  secret:
    key: ${naver.secret.key}
