


spring:
  redis:
    host: ${redis.url}
    port: 6379

  rabbitmq:
    url: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    queue:
      email: "queue:email"
    exchange:
      email: "exchange:email"
    routing:
      email: "key:email"
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL}:9092
    topic:
      email: "email"
    group: "group.email"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google.email.sender}
    password: ${google.app.pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분